In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Array created:\n",a)

Array created:
 [[1 2 3]
 [4 5 6]]


In [2]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
c=np.full((3,3),6)
print("Array with 6's:\n",c)

Array with 6's:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [6]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.27909381 0.26565905]
 [0.45919234 0.79826266]]


In [7]:
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [9]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [10]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
flarr=arr.flatten()
print("\n Original array:\n",arr)
print("\n Flattend array:\n",flarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Flattend array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [11]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n No.of.dimensions:\n",arr.ndim)
print("\n Shape of array:\n",arr.shape)
print("\n Size of array:\n",arr.size)
print("\n Array type:\n",arr.dtype)
newtype=arr.astype('f')
print("\n Converted array element:\n",newtype)
print("\n Converted array type:\n",newtype.dtype)


 No.of.dimensions:
 2

 Shape of array:
 (3, 4)

 Size of array:
 12

 Array type:
 int32

 Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 Converted array type:
 float32


In [12]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:,1])
c=p.astype('f')
print(c)
e=p.astype('i')
print(e)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[ 2  5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
